# Generated by Django 2.2 on 2021-07-27 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usesrs',
            new_name='Users',
        ),
    ]
